/*
Created: 13/04/2016
Modified: 22/09/2016
Project: KRIFT 
Model: MySQL 5.6
Author: Ulisses S. Alves
Version: 2
Database: MySQL 5.6
*/




-- Create tables section -------------------------------------------------

-- Table USUARIO CADASTRADO

CREATE TABLE `USUARIO CADASTRADO`
(
  `NOM_LOGIN` Varchar(20) NOT NULL,
  `SEQ_IMAGEM` Serial NOT NULL,
  `NOM_PERFIL_USUARIO` Varchar(80) NOT NULL,
  `DAT_CADASTRO` Datetime NOT NULL,
  `EMAIL` Varchar(256) NOT NULL,
  `SENHA` Char(41) NOT NULL,
  `DES_USUARIO` Varchar(255),
  `IDT_TENDENCIA` Char(1) NOT NULL,
  `DAT_NASCIMENTO` Date NOT NULL
)
;

CREATE INDEX `IX_Relationship20` ON `USUARIO CADASTRADO` (`SEQ_IMAGEM`)
;

ALTER TABLE `USUARIO CADASTRADO` ADD  PRIMARY KEY (`NOM_LOGIN`)
;

-- Table RECEITA

CREATE TABLE `RECEITA`
(
  `NRO_SEQ_RECEITA` Serial NOT NULL,
  `NOM_LOGIN` Varchar(20) NOT NULL,
  `NOM_RECEITA` Varchar(40) NOT NULL,
  `DES_RECEITA` Varchar(255) NOT NULL,
  `DAT_PUBLICACAO` Date NOT NULL,
  `IDT_TENDENCIA` Char(1) NOT NULL,
  `QTD_TEMPO` Int NOT NULL,
  `QTD_RENDIMENTO` Int NOT NULL
)
;

CREATE INDEX `IX_Relationship1` ON `RECEITA` (`NOM_LOGIN`)
;

ALTER TABLE `RECEITA` ADD  PRIMARY KEY (`NRO_SEQ_RECEITA`)
;

-- Table INGREDIENTE

CREATE TABLE `INGREDIENTE`
(
  `COD_RECEITA` Serial NOT NULL,
  `DES_QUANTIDADE` Varchar(10) NOT NULL,
  `IDT_UNIDADE` Char(40) NOT NULL,
  `NOM_INGREDIENTE` Char(20) NOT NULL
)
;

ALTER TABLE `INGREDIENTE` ADD  PRIMARY KEY (`COD_RECEITA`)
;

-- Table AVALIACAO

CREATE TABLE `AVALIACAO`
(
  `NRO_SEQ_RECEITA` Serial NOT NULL,
  `NOM_LOGIN` Varchar(20) NOT NULL,
  `VLR_AVALIAÇAO` Tinyint NOT NULL
)
;

ALTER TABLE `AVALIACAO` ADD  PRIMARY KEY (`NRO_SEQ_RECEITA`,`NOM_LOGIN`)
;

-- Table COMENTARIO

CREATE TABLE `COMENTARIO`
(
  `NOM_LOGIN` Varchar(20) NOT NULL,
  `NRO_SEQ_RECEITA` Serial NOT NULL,
  `DAT_PUBLICACAO` Datetime NOT NULL,
  `DES_COMENTARIO` Varchar(255) NOT NULL
)
;

ALTER TABLE `COMENTARIO` ADD  PRIMARY KEY (`DAT_PUBLICACAO`,`NRO_SEQ_RECEITA`,`NOM_LOGIN`)
;

-- Table PROCEDIMENTO

CREATE TABLE `PROCEDIMENTO`
(
  `COD_PROCEDIMENTO` Int NOT NULL,
  `NRO_SEQ_RECEITA` Serial NOT NULL,
  `DES_PROCEDIMENTO` Varchar(255) NOT NULL
)
;

ALTER TABLE `PROCEDIMENTO` ADD  PRIMARY KEY (`COD_PROCEDIMENTO`,`NRO_SEQ_RECEITA`)
;

-- Table Denuncia

CREATE TABLE `Denuncia`
(
  `NRO_SEQ_RECEITA` Serial NOT NULL,
  `IDT_TIPO` Char(2) NOT NULL,
  `DES_COMENTARIO` Varchar(255)
)
;

ALTER TABLE `Denuncia` ADD  PRIMARY KEY (`NRO_SEQ_RECEITA`)
;

-- Table HISTORICO

CREATE TABLE `HISTORICO`
(
  `NOM_LOGIN` Varchar(20) NOT NULL,
  `NRO_SEQ_RECEITA` Serial NOT NULL,
  `DAT_ACESSO` Datetime NOT NULL
)
;

ALTER TABLE `HISTORICO` ADD  PRIMARY KEY (`NOM_LOGIN`,`NRO_SEQ_RECEITA`,`DAT_ACESSO`)
;

-- Table CATEGORIA

CREATE TABLE `CATEGORIA`
(
  `SEQ_CATEGORIA` Serial NOT NULL,
  `DES_CATEGORIA` Varchar(20) NOT NULL
)
;

ALTER TABLE `CATEGORIA` ADD  PRIMARY KEY (`SEQ_CATEGORIA`)
;

-- Table Imagem_Usuario

CREATE TABLE `Imagem_Usuario`
(
  `SEQ_IMAGEM` Serial NOT NULL,
  `ARQ_IMAGEM` Blob NOT NULL
)
;

ALTER TABLE `Imagem_Usuario` ADD  PRIMARY KEY (`SEQ_IMAGEM`)
;

-- Table Imagem_Receita

CREATE TABLE `Imagem_Receita`
(
  `NRO_SEQ_RECEITA` Serial NOT NULL,
  `NRO_SEQ_IMAGEM` Serial NOT NULL,
  `ARQ_IMAGEM` Blob NOT NULL
)
;

CREATE INDEX `IX_Relationship22` ON `Imagem_Receita` (`NRO_SEQ_RECEITA`)
;

ALTER TABLE `Imagem_Receita` ADD  PRIMARY KEY (`NRO_SEQ_RECEITA`,`NRO_SEQ_IMAGEM`)
;

-- Table CATEGORIA_RECEITA

CREATE TABLE `CATEGORIA_RECEITA`
(
  `NRO_SEQ_RECEITA` Serial NOT NULL,
  `SEQ_CATEGORIA` Serial NOT NULL
)
;

ALTER TABLE `CATEGORIA_RECEITA` ADD  PRIMARY KEY (`NRO_SEQ_RECEITA`,`SEQ_CATEGORIA`)
;

-- Table PREFERENCIAS

CREATE TABLE `PREFERENCIAS`
(
  `NOM_LOGIN` Varchar(20) NOT NULL,
  `SEQ_CATEGORIA` Serial NOT NULL
)
;

ALTER TABLE `PREFERENCIAS` ADD  PRIMARY KEY (`NOM_LOGIN`,`SEQ_CATEGORIA`)
;

-- Table FAVORITO

CREATE TABLE `FAVORITO`
(
  `NOM_LOGIN` Varchar(20) NOT NULL,
  `NRO_SEQ_RECEITA` Serial NOT NULL
)
;

ALTER TABLE `FAVORITO` ADD  PRIMARY KEY (`NOM_LOGIN`,`NRO_SEQ_RECEITA`)
;

-- Create relationships section ------------------------------------------------- 

ALTER TABLE `RECEITA` ADD CONSTRAINT `Relationship1` FOREIGN KEY (`NOM_LOGIN`) REFERENCES `USUARIO CADASTRADO` (`NOM_LOGIN`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `INGREDIENTE` ADD CONSTRAINT `Relationship2` FOREIGN KEY (`COD_RECEITA`) REFERENCES `RECEITA` (`NRO_SEQ_RECEITA`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `AVALIACAO` ADD CONSTRAINT `Relationship13` FOREIGN KEY (`NRO_SEQ_RECEITA`) REFERENCES `RECEITA` (`NRO_SEQ_RECEITA`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `COMENTARIO` ADD CONSTRAINT `Relationship14` FOREIGN KEY (`NRO_SEQ_RECEITA`) REFERENCES `RECEITA` (`NRO_SEQ_RECEITA`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `HISTORICO` ADD CONSTRAINT `Relationship16` FOREIGN KEY (`NOM_LOGIN`) REFERENCES `USUARIO CADASTRADO` (`NOM_LOGIN`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `HISTORICO` ADD CONSTRAINT `Relationship17` FOREIGN KEY (`NRO_SEQ_RECEITA`) REFERENCES `RECEITA` (`NRO_SEQ_RECEITA`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `USUARIO CADASTRADO` ADD CONSTRAINT `Relationship20` FOREIGN KEY (`SEQ_IMAGEM`) REFERENCES `Imagem_Usuario` (`SEQ_IMAGEM`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `Imagem_Receita` ADD CONSTRAINT `Relationship22` FOREIGN KEY (`NRO_SEQ_RECEITA`) REFERENCES `RECEITA` (`NRO_SEQ_RECEITA`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `COMENTARIO` ADD CONSTRAINT `Relationship23` FOREIGN KEY (`NOM_LOGIN`) REFERENCES `USUARIO CADASTRADO` (`NOM_LOGIN`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `AVALIACAO` ADD CONSTRAINT `Relationship24` FOREIGN KEY (`NOM_LOGIN`) REFERENCES `USUARIO CADASTRADO` (`NOM_LOGIN`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `CATEGORIA_RECEITA` ADD CONSTRAINT `Relationship32` FOREIGN KEY (`SEQ_CATEGORIA`) REFERENCES `CATEGORIA` (`SEQ_CATEGORIA`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `CATEGORIA_RECEITA` ADD CONSTRAINT `Relationship33` FOREIGN KEY (`NRO_SEQ_RECEITA`) REFERENCES `RECEITA` (`NRO_SEQ_RECEITA`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `PREFERENCIAS` ADD CONSTRAINT `Relationship34` FOREIGN KEY (`SEQ_CATEGORIA`) REFERENCES `CATEGORIA` (`SEQ_CATEGORIA`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `PREFERENCIAS` ADD CONSTRAINT `Relationship35` FOREIGN KEY (`NOM_LOGIN`) REFERENCES `USUARIO CADASTRADO` (`NOM_LOGIN`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `Denuncia` ADD CONSTRAINT `Relationship36` FOREIGN KEY (`NRO_SEQ_RECEITA`) REFERENCES `RECEITA` (`NRO_SEQ_RECEITA`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `FAVORITO` ADD CONSTRAINT `Relationship39` FOREIGN KEY (`NOM_LOGIN`) REFERENCES `USUARIO CADASTRADO` (`NOM_LOGIN`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `FAVORITO` ADD CONSTRAINT `Relationship40` FOREIGN KEY (`NRO_SEQ_RECEITA`) REFERENCES `RECEITA` (`NRO_SEQ_RECEITA`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `PROCEDIMENTO` ADD CONSTRAINT `Relationship41` FOREIGN KEY (`NRO_SEQ_RECEITA`) REFERENCES `RECEITA` (`NRO_SEQ_RECEITA`) ON DELETE RESTRICT ON UPDATE RESTRICT
;



